[package]
name = "ch2rs"
version = "0.1.0"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
clickhouse = "*"
heck = "0.3.2"
reflection = "0.1.3"
serde = { version = "1.0.126", features = ["derive"] }
tokio = { version = "1.6.0", features = ["macros"] }
